### ISSUE TITLE
[1.12.2] Colored backpacks Dupe

### ISSUE THREAD

**Issue by CDAGaming** [gr8pefish/IronBackpacks#223]
#### Issue Description//What happens?:
While experimenting with this mod, placing an Iron Backpack with any dye causes a NoMethodError in Logs as well as duplicating the first item you take out of the crafting bench.

#### What you expected to happen:
Recipe to function Properly (Cant really explain this well)

#### Steps to reproduce (important):

1. Get an Iron Backpack and Any Dye
2. Use a Crafting Bench to put the 2 items in as normal for a Colored backpack
3. Nothing will appear in the output, and taking out the first item will dupe it x2.
...

#### Error Log:
https://hastebin.com/vulububuko.rb

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.12.2-3.0.5-6
- Minecraft: 1.12.2
- Forge: 14.23.2.2615

**Comment by Vizis** [comment]
Basic BP also can duplicate!
Only Gold and Diamon are bug free
OFC at duplicate we got HUUGE error in console :)

**Comment by nok-ko** [comment]
I can't duplicate this issue at all. Everything appears to work fine in 1.12.2-3.0.5-6, in a single-player world. I tried to reproduce this with an iron backpack and red dye, leather backpack and red dye, and with the crafting recipe all over the crafting table... no dice. 
Could you supply a video or more detailed reproduction instructions?

**Comment by CDAGaming** [comment]
Sure. I'll see if i can make one later today

**Comment by AdaraChristine** [comment]
IronBackpacks-1.12.2-3.0.7-10
Forge 14.23.3.2655
I can confirm this happens on a MP server only. Basic backpack and 1 dye in a crafting table does not produce an output but when you take out the dye it dupes. The pack does not tho.

[21:44:04] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: 
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: 
	at gr8pefish.ironbackpacks.core.recipe.ColorBackpackRecipe.getDyeColor(ColorBackpackRecipe.java:57) ~[ColorBackpackRecipe.class:1.12.2-3.0.7-10]
	at gr8pefish.ironbackpacks.core.recipe.ColorBackpackRecipe.func_77572_b(ColorBackpackRecipe.java:40) ~[ColorBackpackRecipe.class:1.12.2-3.0.7-10]
	at net.minecraft.inventory.Container.func_192389_a(Container.java:798) ~[afr.class:?]
	at net.minecraft.inventory.ContainerWorkbench.func_75130_a(SourceFile:51) ~[afz.class:?]
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:93) ~[afy.class:?]
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70) ~[agr.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:195) ~[afr.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1158) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by willbattel** [comment]
Just got this as well on our private server running FTB Revelation. Trying to dye the backpack causes this error in the server console, and the crafting is immediately "undone" from the player's POV.

```
[Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.BootstrapMethodError: java.lang.NoSuchMethodError:
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.BootstrapMethodError: java.lang.NoSuchMethodError:
        at gr8pefish.ironbackpacks.core.recipe.ColorBackpackRecipe.getDyeColor(ColorBackpackRecipe.java:57) ~[ColorBackpackRecipe.class:1.12.2-3.0.8-12]
        at gr8pefish.ironbackpacks.core.recipe.ColorBackpackRecipe.func_77572_b(ColorBackpackRecipe.java:40) ~[ColorBackpackRecipe.class:1.12.2-3.0.8-12]
        at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:201) ~[aku.class:?]
        at jds.bibliocraft.containers.ContainerFancyWorkbench.func_75130_a(ContainerFancyWorkbench.java:104) ~[ContainerFancyWorkbench.class:?]
        at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:93) ~[afy.class:?]
        at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70) ~[agr.class:?]
        at net.minecraft.inventory.Container.func_184996_a(Container.java:281) ~[afr.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1160) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
Caused by: java.lang.NoSuchMethodError:
        at gr8pefish.ironbackpacks.core.recipe.ColorBackpackRecipe.getDyeColor(ColorBackpackRecipe.java:57) ~[ColorBackpackRecipe.class:1.12.2-3.0.8-12]
        at gr8pefish.ironbackpacks.core.recipe.ColorBackpackRecipe.func_77572_b(ColorBackpackRecipe.java:40) ~[ColorBackpackRecipe.class:1.12.2-3.0.8-12]
        at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:201) ~[aku.class:?]
        at jds.bibliocraft.containers.ContainerFancyWorkbench.func_75130_a(ContainerFancyWorkbench.java:104) ~[ContainerFancyWorkbench.class:?]
        at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:93) ~[afy.class:?]
        at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70) ~[agr.class:?]
        at net.minecraft.inventory.Container.func_184996_a(Container.java:281) ~[afr.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1160) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
```

**Comment by ineternet** [comment]
I just quickly wanted to add that this issue is still present in 1.12.2-3.0.8-12. Different crafting tables seem to create different results, and I can't really describe what happens myself, but I'm able to dupe either my basic backpack or the dye every time. This is on a MP server.
https://gfycat.com/WeeKeenHermitcrab
